---
name: ci

on: push

permissions:
  contents: read

jobs:
  build:
    name: Material
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Build and zip
        run: make -C www/m release
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: material
          path: dist/*.zip
          if-no-files-found: error

  tiled:
    name: Tiled
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: cd www/t && npm i
      - name: Build
        run: make -C www/t build
      - name: Zip
        run: make -C www/t dist
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: tiled
          path: dist/*.zip
          if-no-files-found: error

  panels:
    name: Panels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: cd www/p && npm i
      - name: Build
        run: make -C www/p
      - name: Create release
        run: make -C www/p release
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: panels
          path: dist/*.zip
          if-no-files-found: error

  enyo:
    name: Enyo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: cd www/enyo && npm i
      - name: Build
        run: make -C www/enyo build
      - name: Zip
        run: make -C www/enyo dist
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: enyo
          path: dist/*.zip
          if-no-files-found: error
